spring.application.name=quest-log
spring.datasource.url=jdbc:postgresql://localhost:5432/quest-log
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update